name = "cc-statusline-rs"
version = "0.7.0"
description = "An opinionated ANSI statusline for Claude Code"
homepage = "https://github.com/ceejbot/cc-statusline-rs"
license = "Apache-2.0"
repository = "https://github.com/ceejbot/cc-statusline-rs"
