[package]
name = "cc-statusline-rs"
version = "0.6.1"
edition = "2024"
rust-version = "1.85"
description = "An opinionated ANSI statusline for Claude Code"
license = "Apache-2.0"
repository = "https://github.com/ceejbot/cc-statusline-rs"

[lib]
name = "cc_statusline_rs"
path = "src/lib.rs"

[[bin]]
name = "cc-statusline-rs"
path = "src/main.rs"

[dependencies]
jiff = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
panic = "abort"

[lints.rust]
future_incompatible = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
trivial_casts = "warn"

[lints.clippy]
unwrap_used = "deny"
