---
name: release
permissions:
    contents: read

on:
    push:
        tags:
            - "v**[0-9]+.[0-9]+.[0-9]+*"
    workflow_dispatch:
        inputs:
            ref_name:
                type: string
                description: the refname to build a release from
                default: "main"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    preflight:
        permissions:
            contents: write
        name: preflight
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                persist-credentials: false

            - name: get stable + nightly Rust
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
              with:
                  toolchain: nightly, stable
                  target: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu
                  components: clippy, rustfmt
                  cache-directories: |
                      ~/.cargo/registry
                      ~/.cargo/bin
                      target
                  cache: false

            - name: consult Clippy
              run: cargo +stable clippy --all-targets -- -D warnings

            - name: check formatting
              run: cargo +nightly fmt --check --all

            - name: set ref_name
              shell: bash
              run: |
                if [ -n "${INPUTS_REF_NAME}" ]; then
                  echo "REF_NAME=${INPUTS_REF_NAME}" >> $GITHUB_ENV
                else
                  echo "REF_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
                fi
              env:
                INPUTS_REF_NAME: ${{ inputs.ref_name }}

            - name: create github release
              continue-on-error: true # for testing
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  release_url=$(gh release create $REF_NAME --generate-notes)

            - name: build for release and upload
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  INPUTS_REF_NAME: ${{ inputs.ref_name }}
              run: |
                  REF_NAME="${GITHUB_REF_NAME}"
                  if [ -n "${INPUTS_REF_NAME}" ]; then
                      REF_NAME="${INPUTS_REF_NAME}"
                  fi
                  cargo +stable build --release
                  tar czf cc-statusline-rs-x86_64-unknown-linux-gnu.tar.gz --strip-components=2  target/release/cc-statusline-rs
                  gh release upload "$REF_NAME" "cc-statusline-rs-x86_64-unknown-linux-gnu.tar.gz"


    release-macos:
        permissions:
            contents: write
        name: release-macos
        runs-on: macos-latest
        needs: preflight
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                persist-credentials: false

            - name: get stable Rust
              uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
              with:
                  toolchain: stable
                  target: aarch64-apple-darwin
                  cache-directories: |
                      ~/.cargo/registry
                      ~/.cargo/bin
                      target
                  cache: false

            - name: build for release
              run: |
                  cargo +stable build --release --target aarch64-apple-darwin

            - name: upload release assets
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  INPUTS_REF_NAME: ${{ inputs.ref_name }}
              run: |
                  REF_NAME="${GITHUB_REF_NAME}"
                  if [ -n "${INPUTS_REF_NAME}" ]; then
                      REF_NAME="${INPUTS_REF_NAME}"
                  fi
                  target=aarch64-apple-darwin
                  mkdir -p dist
                  cd dist
                  tar czf cc-statusline-rs-$target.tar.gz --strip-components=4  ../target/$target/release/cc-statusline-rs
                  gh release upload "$REF_NAME" "cc-statusline-rs-$target.tar.gz"
